# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni_data',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('current_status', models.CharField(blank=True, max_length=300, null=True)),
                ('batch', models.CharField(blank=True, max_length=4, null=True)),
                ('company_institue', models.CharField(blank=True, max_length=300, null=True)),
                ('designation', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('skill', models.CharField(blank=True, max_length=200, null=True)),
                ('other', tinymce.models.HTMLField()),
                ('linkedin_url', models.CharField(blank=True, max_length=500, null=True)),
                ('github_url', models.CharField(blank=True, max_length=500, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default='/media/default.png', upload_to='alumni_images/')),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
