# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area_of_interest_data',
            fields=[
                ('faculty_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('area_of_interest', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_data',
            fields=[
                ('faculty_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('designation', models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Temporary Faculty', 'Temporary Faculty')], max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='other_details',
            fields=[
                ('faculty_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('other_details', models.CharField(blank=True, max_length=8000, null=True)),
            ],
        ),
    ]
