# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20170217_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_details',
            name='other_details',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
    ]
