# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20170217_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_details_data',
            fields=[
                ('faculty_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('other_details', tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(
            name='other_details',
        ),
    ]
