# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_auto_20170218_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_data',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_data',
            name='faculty_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty_data',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
