# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20170219_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_data',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='faculty_images/'),
        ),
    ]
