# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement_data',
            name='subtitle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
