# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement_data',
            name='content',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
