# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20170403_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement_data',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
