# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 07:35
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20170403_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement_data',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
