# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_data',
            fields=[
                ('login_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(choices=[(1, 'student'), (2, 'faculty'), (3, 'alumni'), (4, 'admin'), (5, 'developer')], default=0)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('email_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
