# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_login_data_content_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_data',
            name='otp',
        ),
    ]
