# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_data',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
