# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumni_data_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_data',
            name='enroll_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
