# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_send_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('email_data', models.TextField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='custom_keys_data',
            name='value',
            field=models.TextField(),
        ),
    ]
