# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 12:57
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_key', '0002_auto_20170220_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_send_data',
            name='email_data',
            field=tinymce.models.HTMLField(),
        ),
    ]
