# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_data',
            new_name='notice_data',
        ),
    ]
