# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20170220_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_data',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
