# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_data',
            fields=[
                ('login_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('group_id', models.SmallIntegerField(default=0)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
