# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170219_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_data',
            name='group_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='login_data',
            name='login_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
