# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sem', models.IntegerField(default=0)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=500, null=True)),
                ('github_url', models.CharField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(default='media/default.png', upload_to='student_images/')),
                ('skill', tinymce.models.HTMLField()),
            ],
        ),
    ]
