# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='photo',
            field=models.ImageField(default='media/default.png', upload_to='student_images/'),
        ),
    ]
