# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 13:43
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170305_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='skill',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
