# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_keys_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='keys_data',
        ),
    ]
