# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 20:58
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_key', '0002_auto_20170219_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_keys_data',
            name='email_connect',
            field=tinymce.models.HTMLField(default=113),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom_keys_data',
            name='email_verify',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
