# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_key', '0003_auto_20170219_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_send_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verify', tinymce.models.HTMLField()),
                ('email_connect', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='custom_keys_data',
            name='email_connect',
        ),
        migrations.RemoveField(
            model_name='custom_keys_data',
            name='email_verify',
        ),
    ]
