# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_key', '0005_auto_20170219_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_send_data',
            name='email_data',
            field=models.TextField(),
        ),
    ]
