# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('enroll_no', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sem', models.SmallIntegerField(choices=[('1st semester', 1), ('2nd semester', 2), ('3rd semester', 3), ('4th semester', 4), ('5th semester', 5), ('6th semester', 6), ('7th semester', 7), ('8th semester', 8)], default=0)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=500, null=True)),
                ('github_url', models.CharField(blank=True, max_length=500, null=True)),
                ('achivement', models.CharField(blank=True, max_length=500, null=True)),
                ('achivement_url', models.CharField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(default='/media/default.png', upload_to='/media/student_images/')),
                ('skill', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
