# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='sem',
            field=models.SmallIntegerField(choices=[(1, '1st semester'), (2, '2nd semester'), (3, '3rd semester'), (4, '4th semester'), (5, '5th semester'), (6, '6th semester'), (7, '7th semester'), (8, '8th semester')], default=0),
        ),
    ]
