# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20170217_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_data',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill_data',
            name='enroll_no',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
