# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20170217_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='sem',
            field=models.SmallIntegerField(default=0),
        ),
    ]
