# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20170219_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill_data',
            old_name='enroll_no',
            new_name='roll_no',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='enroll_no',
            new_name='roll_no',
        ),
    ]
